sudo: false

services:
  - docker

matrix:
  allow_failures:
    - php: hhvm
    - php: nightly

before_script:
  - docker build -t maestro .

script:
  - docker run maestro bash -c "./vendor/bin/phpunit"
  - docker run maestro bash -c "./vendor/bin/phpunit --coverage-text"
